<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:PE"
  xmlns:tns="urn:com:appian:types:PE" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PE_SFTP_FULL_ACCOMPLISH">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="PE_SFTP_FULL_ACCOMPLISH")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000eb9d-702a-8000-9a95-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000eb9d-702a-8000-9a95-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="accomplishmentId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="ACCOMPLISHMENT_ID", nullable=false, unique=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="accomplishment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ACCOMPLISHMENT", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="accompCategory" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ACCOMP_CATEGORY", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="country" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="COUNTRY", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="state" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="STATE", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dtIssued" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="DT_ISSUED", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="emplid" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EMPLID", columnDefinition="VARCHAR(21)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="expiratnDt" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EXPIRATN_DT", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="issuedBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ISSUED_BY", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="lastupddttm" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="LASTUPDDTTM", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="licenseNbr" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="LICENSE_NBR", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="licenseVerified" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="LICENSE_VERIFIED", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="passed" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PASSED", columnDefinition="VARCHAR(21)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="renewal" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="RENEWAL", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="score" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="SCORE", columnDefinition="VARCHAR(21)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
