<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:PE"
  xmlns:tns="urn:com:appian:types:PE" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PE_SFTP_FULL_CITIZENSHIP">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="PE_SFTP_FULL_CITIZENSHIP")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ecd2-dfdf-8000-b40b-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000ecd2-dfdf-8000-b40b-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="citizenshipId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="CITIZENSHIP_ID", nullable=false, unique=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="citizenshipStatus" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="CITIZENSHIP_STATUS", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="country" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="COUNTRY", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="effdt" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EFFDT", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="emplid" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EMPLID", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="expiratnDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EXPIRATN_DATE", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
