<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:PE"
  xmlns:tns="urn:com:appian:types:PE" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="PE_SFTP_PS_FULL_PERSONAL">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="PE_SFTP_PS_FULL_PERSONAL")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ef90-28ab-8000-c55b-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000eb9c-fe6f-8000-9a56-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000ef90-28ab-8000-c55b-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="psFullPersonalId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="PS_FULL_PERSONAL_ID", nullable=false, unique=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="emplClass" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EMPL_CLASS", columnDefinition="VARCHAR(21)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="emplid" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="EMPLID", columnDefinition="VARCHAR(21)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fname" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="FNAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="hireDt" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="HIRE_DT", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jobFamily" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="JOB_FAMILY", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="lname" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="LNAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="location" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="LOCATION", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="midname" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="midname", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="name" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="NAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="perStatus" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PER_STATUS", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmEmailAdd" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_EMAIL_ADD", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmPerformMgr" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_PERFORM_MGR", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rehireDt" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="REHIRE_DT", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmSubsegmentCd" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SUBSEGMENT_CD", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="deptid" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="DEPTID", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="adjSvcDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ADJ_SVC_DATE", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jobcode" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="JOBCODE", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jobEntryDt" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="JOB_ENTRY_DT", columnDefinition="VARCHAR(55)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmPriIndLob" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_PRI_IND_LOB", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmPriIndSector" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_PRI_IND_SECTOR", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmSecIndLob" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SEC_IND_LOB", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmSecIndSector" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SEC_IND_SECTOR", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="prefFirstName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PREF_FIRST_NAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="prefLastName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PREF_LAST_NAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="prefMiddleName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PREF_MIDDLE_NAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="prefName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PREF_NAME", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="adjustedServiceDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ADJUSTED_SERVICE_DATE", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="yos" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="YOS", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="State" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="State", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="PM_PRI_IND_SEGMT" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_PRI_IND_SEGMT", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="PM_SEC_IND_SEGMT" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SEC_IND_SEGMT", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
