<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types"
  xmlns:tns="urn:com:appian:types" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_SFTP_PSSubsegment">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_SFTP_PS_SUBSEGMENT")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000e6e5-d312-8000-a83a-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0001e6d3-6a03-8000-9f05-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6e5-d312-8000-a83a-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="psSubsegmentId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="PS_SUBSEGMENT_ID", nullable=false, unique=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmSubsegmentCd" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SUBSEGMENT_CD", columnDefinition="VARCHAR(11)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmService2" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SERVICE_2", columnDefinition="VARCHAR(4)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pmService" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="PM_SERVICE", columnDefinition="VARCHAR(4)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="descr" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="DESCR", columnDefinition="VARCHAR(31)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="descrshort" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="DESCRSHORT", columnDefinition="VARCHAR(11)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
