<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:CAW"
  xmlns:tns="urn:com:appian:types:CAW" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_V_NOMINATION">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_V_NOMINATION")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000eeca-7ac4-8000-bf1c-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e6db-3671-8000-a136-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6e4-8519-8000-a759-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6eb-3bea-8000-a976-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6f7-100f-8000-ad4f-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6f8-3d33-8000-ad62-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e74a-1c5e-8000-c69e-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e775-e673-8000-d760-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e801-59fa-8000-faec-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e813-ff30-8000-fef7-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e82c-ddec-8000-046b-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000ea48-db79-8000-6f65-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000ea58-c11b-8000-71b8-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000eeca-7ac4-8000-bf1c-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[cdt for CAW_V_NOMINATION]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="nominationId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationId", nullable=false, columnDefinition="INT") @Id</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationType", nullable=false, columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="positionTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="positionTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="positionType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="positionType", nullable=false, columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="subPositionTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="subPositionTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="subPosition" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="subPosition", nullable=false, columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="statusId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="statusId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationStatus" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationStatus", nullable=false, columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="employeeId" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="employeeId", columnDefinition="VARCHAR(12)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="firstName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="firstName", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="middleName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="middleName", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="lastName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="lastName", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nonTraditionalTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nonTraditionalTypeId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nonTradRotationalType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nonTradRotationalType", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherNonTraditionalRotationType"
        nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherNonTraditionalRotationType", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fullName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fullName", columnDefinition="VARCHAR(302)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nonUsEmail" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nonUsEmail", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="functionName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="functionName", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherFunctionName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherFunctionName", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="levelName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="levelName", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jobDescription" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="jobDescription", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ismemberFirmpartner" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ismemberFirmpartner", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="currentPML" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="currentPML", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="origMemberFirmCountry" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="origMemberFirmCountry", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returningMemberFirmCountry" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returningMemberFirmCountry", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherOriginatingRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherOriginatingRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherOriginatingBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherOriginatingBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherOriginatingHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherOriginatingHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returnRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returnRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherReturningRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherReturningRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returnBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returnBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherReturningBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherReturningBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returnHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returnHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherReturningHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherReturningHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="applicablePathway" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="applicablePathway", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pathwayComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="pathwayComments", columnDefinition="VARCHAR(250)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="yearsWithFirm" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="yearsWithFirm", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="applicablePathwayHR" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="applicablePathwayHR", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="mdPromotionDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="mdPromotionDate", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="mdPromotionDateComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="mdPromotionDateComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="partnerPromotionDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="partnerPromotionDate", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="partnerPromotionDateComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="partnerPromotionDateComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="clientConsiderationComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="clientConsiderationComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rationalForNomination" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="rationalForNomination", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isPcaob" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isPcaob", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isIsa" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isIsa", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isIfrsb" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isIfrsb", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isUsGaapb" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isUsGaapb", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isAicpa" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isAicpa", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pcaobLevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="pcaobLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isaLevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isaLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ifrsbLevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ifrsbLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="usGaapbLevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="usGaapbLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="aicpaLevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="aicpaLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="recommendedDppGroupId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="recommendedDppGroupId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroup" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroup", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroupOtherComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroupOtherComment", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleConsideration" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleConsideration", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isOtherLanguage" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isOtherLanguage", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="languageOtherThanEng" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="languageOtherThanEng", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="hasCpaLicense" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="hasCpaLicense", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="statesForCpaLicence" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="statesForCpaLicence", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="primaryIndustryId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="primaryIndustryId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="primaryIndustryOther" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="primaryIndustryOther", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="industry" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="industry", nullable=false, columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isPotentialSec_FasbCandidate" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isPotentialSec_FasbCandidate", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isAqspNomination" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isAqspNomination", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="anticipatedStartDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="anticipatedStartDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="anticipatedEndDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="anticipatedEndDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isVettingRequired" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isVettingRequired", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isDirectHire" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isDirectHire", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isInterviewRequested" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isInterviewRequested", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isInterviewConducted" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isInterviewConducted", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isReadyForOnboarding" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isReadyForOnboarding", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isFuturePartnerPromote" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isFuturePartnerPromote", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isDirectHireInternal" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isDirectHireInternal", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fiscalYear" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fiscalYear", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="askID" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="askID", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="buID" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="buID", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="intakeSent" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="intakeSent", columnDefinition="varbinary")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isActive" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isActive", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdOn" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedOn" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isNonAuditLeader" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isNonAuditLeader", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
