<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:CAW"
  xmlns:tns="urn:com:appian:types:CAW" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_V_REPORT_NOMINATION">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_V_REPORT_NOMINATION")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000e814-36ab-8000-ff0d-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e814-36ab-8000-ff0d-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[Data needed for the none Rotational Ask  portion of the ASK vs Nomination report]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="generatedId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @Column(name="generatedId", nullable=false, columnDefinition="BIGINT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fiscalYear" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fiscalYear", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="buId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="buId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="regionId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="regionId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="transitionalComplete" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="transitionalComplete", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="transitionalInProcess" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="transitionalInProcess", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherCoreComplete" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherCoreComplete", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherCoreInProcess" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherCoreInProcess", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherRotationalComplete" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherRotationalComplete", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherRotationalInProcess" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherRotationalInProcess", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
