<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:CAW"
  xmlns:tns="urn:com:appian:types:CAW" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_V_STATUS_SUMMARY">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_V_STATUS_SUMMARY")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000eb80-5185-8000-9733-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e788-0978-8000-da80-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e800-3cc8-8000-faa4-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e837-f045-8000-0851-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e838-99cc-8000-08b9-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e838-b1da-8000-08bd-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000eb80-5185-8000-9733-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="nominationGeneratedId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @Column(name="nominationGeneratedId", nullable=false, columnDefinition="BIGINT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fiscalYear" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fiscalYear", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="positionTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="positionTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="positionType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="positionType", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="subPositionTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="subPositionTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="subPosition" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="subPosition", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationStatus" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationStatus", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fullName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fullName", columnDefinition="VARCHAR(303)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="submittedOn" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="submittedOn", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="OpsReview" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="OpsReview", nullable=false, columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="inspectionReviewCompletedDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="inspectionReviewCompletedDate", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="hrReviewCompletedDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="hrReviewCompletedDate", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isOpsAdditionalVettingReq" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isOpsAdditionalVettingReq", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="opsAdditionalVettingCompletedDate"
        nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="opsAdditionalVettingCompletedDate", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="interviewCompletedDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="interviewCompletedDate", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="officeVisitCompletedDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="officeVisitCompletedDate", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="approvedOn" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="approvedOn", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="approvedBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="approvedBy", columnDefinition="VARCHAR(7)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="offerSent" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="offerSent", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="candidateResponse" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="candidateResponse", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="transConfirmationSent" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="transConfirmationSent", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="transConfirmationAck" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="transConfirmationAck", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="intakeFormSent" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="intakeFormSent", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="intakeFormReceived" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="intakeFormReceived", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="vettingComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="vettingComments", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isVettingRequired" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isVettingRequired", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationTypeId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
