<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:CAW"
  xmlns:tns="urn:com:appian:types:CAW" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_V_CORE_ASK">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_V_CORE_ASK")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ebb8-e19d-8000-9cc9-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e6a5-23f8-8000-893f-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6ad-382d-8000-8e7b-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6b6-728d-8000-925c-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6bb-87f0-8000-939c-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6bb-8c64-8000-93a5-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6c4-fe0a-8000-97f5-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e774-4d83-8000-d6d1-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e837-586f-8000-0824-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e840-a252-8000-0a3d-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000ebb8-e19d-8000-9cc9-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[cdt for CAW_V_CORE_ASK]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="askDetailId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="askDetailId", nullable=false, columnDefinition="INT") @Id</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="askId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="askId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fYear" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fYear", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="recordName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="recordName", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="statusId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="statusId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="status" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="askStatus", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroupId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroupId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroup" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroup", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="needReason" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="needReason", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="levelNeedId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="levelNeedId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="levelNeed" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="levelNeed", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="titlingCategory" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="titlingCategory", columnDefinition="VARCHAR(300)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pml" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="pml", columnDefinition="VARCHAR(99)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="transitionalCoach" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="transitionalCoach", columnDefinition="VARCHAR(99)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="coreAskName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="coreAskName", columnDefinition="VARCHAR(200)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="generalSpecialityNeed" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="generalSpecialityNeed", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rolePosting" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="rolePosting", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="outGoingResource" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="outGoingResource", columnDefinition="VARCHAR(300)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="generalSpecialityNeedcomment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="generalSpecialityNeedComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="headCountAmount" nillable="true" type="xsd:double">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="headCountAmount", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fteAmount" nillable="true" type="xsd:double">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fteAmount", columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="endDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="endDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="projectedStartDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="projectedStartDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleSummary" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleSummary", columnDefinition="VARCHAR(2000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleResponsibility" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleResponsibility", columnDefinition="VARCHAR(2000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleQualification" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleQualification", columnDefinition="VARCHAR(2000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="postingReqnumber" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="postingReqNumber", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="version" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="version", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isActive" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isActive", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isCompleted" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isCompleted", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdOn" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedOn" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
