<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types"
  xmlns:tns="urn:com:appian:types" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_V_CANDIDATE_INTAKE_EXPORT_SHEET2">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_V_CANDIDATE_INTAKE_EXPORT_SHEET2")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000eba4-fe30-8000-9af0-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e826-7999-8000-0349-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000eba4-fe30-8000-9af0-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[cdt for CAW_V_CANDIDATE_INTAKE_EXPORT_SHEET2 view]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="candidateDetailsId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @Column(name="candidateDetailsId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fullName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fullName", columnDefinition="VARCHAR(303)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fiscalYear" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fiscalYear", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isKpmgNationalInstructor" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isKpmgNationalInstructor", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="kpmgInstructorYear" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="kpmgInstructorYear", columnDefinition="VARCHAR(25)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isFacilitatedLocalOfficeTraining"
        nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isFacilitatedLocalOfficeTraining", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isDevelopedLocalOfficeTraining" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isDevelopedLocalOfficeTraining", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isInternationalRotationComplete"
        nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isInternationalRotationComplete", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="internationalRotations" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="internationalRotations", columnDefinition="VARCHAR(500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="internalFirmCommittees" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="internalFirmCommittees", columnDefinition="VARCHAR(500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="clientRelatedCommitments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="clientRelatedCommitments", columnDefinition="VARCHAR(500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nonClientRoles" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nonClientRoles", columnDefinition="VARCHAR(500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherRoles" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherRoles", columnDefinition="VARCHAR(500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="topicTeamInterestInquiries" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="topicTeamInterestInquiries", columnDefinition="TEXT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="topicTeamInterestAccounting" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="topicTeamInterestAccounting", columnDefinition="TEXT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="riskAssessmentExp" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="riskAssessmentExp", columnDefinition="VARCHAR(500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="materialEvalResults" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="materialEvalResults", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="intCtrlFinancialReporting" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="intCtrlFinancialReporting", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="profSkepticism" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="profSkepticism", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="groupAuditScoping" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="groupAuditScoping", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="soc1reports" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="soc1reports", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="cryptoBlockChain" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="cryptoBlockChain", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dataSoftwareTools" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dataSoftwareTools", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="inventoryTools" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="inventoryTools", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="planAccountingAuditIssues" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="planAccountingAuditIssues", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="incomeTaxAccountingIssues" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="incomeTaxAccountingIssues", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="substAnalyticalProcedures" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="substAnalyticalProcedures", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="journalEntries" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="journalEntries", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="deficienciesWeakness" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="deficienciesWeakness", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="goingConcern" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="goingConcern", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="auditReportingMatters" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="auditReportingMatters", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="cams" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="cams", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="repLettersOthers" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="repLettersOthers", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="workPaperAccessDoc" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="workPaperAccessDoc", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="attestationSSARS" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="attestationSSARS", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="estimatesSpecialists" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="estimatesSpecialists", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="languageSkillName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="languageSkillName", columnDefinition="TEXT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="levelOfExperience" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="levelOfExperience", columnDefinition="TEXT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherCandidateIntakeComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherCandidateIntakeComments", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="powerBI" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="powerBI", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
