<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types"
  xmlns:tns="urn:com:appian:types" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_SFTP_IAMIdentityData">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_SFTP_IAM_IDENTITY_DATA")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0001e6d3-6a23-8000-9f07-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0001e6d3-6a23-8000-9f07-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="iamIdentityId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="IAM_IDENTITY_ID", nullable=false, unique=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="msvcsusproduct" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="msvcsUSProduct", columnDefinition="VARCHAR(257)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="msvcsusdeptid" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="msvcsUSDeptID", columnDefinition="VARCHAR(257)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="msvcsemplid" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="msvcsEMPLID", columnDefinition="VARCHAR(257)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="msvcsusgeoarea" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="msvcsUSGeoArea", columnDefinition="VARCHAR(257)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
