<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:CAW"
  xmlns:tns="urn:com:appian:types:CAW" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_V_NOMINATION_EXPORT">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_V_NOMINATION_EXPORT")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ebbf-97a6-8000-9d34-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e775-a926-8000-d73f-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e79a-a1eb-8000-dd31-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e813-e58e-8000-fed8-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e817-db80-8000-ffc1-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e838-02be-8000-0865-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e840-a9f3-8000-0a42-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000eb2f-8dbe-8000-8de8-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000eb9e-dddc-8000-9ac5-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000ebbf-97a6-8000-9d34-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[View for Nomination Export]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="nominationId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @Column(name="nominationId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="recordName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="recordName", columnDefinition="VARCHAR(217)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationType", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="positionTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="positionTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="positionType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="positionType", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="subPositionTypeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="subPositionTypeId", nullable=false, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="subPosition" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="subPosition", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="statusId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="statusId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nominationStatus" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nominationStatus", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="employeeId" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="employeeId", columnDefinition="VARCHAR(12)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fullName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fullName", columnDefinition="VARCHAR(303)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fiscalYear" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fiscalYear", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="functionName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="functionName", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jobDescription" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="jobDescription", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherFunctionName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherFunctionName", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="jobFamily" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="jobFamily", columnDefinition="VARCHAR(50)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ismemberFirmpartner" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ismemberFirmpartner", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="origMemberFirmCountry" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="origMemberFirmCountry", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returningMemberFirmCountry" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returningMemberFirmCountry", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="originatingHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="originatingHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returnRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returnRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherReturningRegion" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherReturningRegion", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returnBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returnBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="nonTradRotationalType" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="nonTradRotationalType", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherReturningBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherReturningBU", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="returnHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="returnHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="otherReturningHomeOffice" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="otherReturningHomeOffice", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="yearsWithFirm" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="yearsWithFirm", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="mdPromotionDate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="mdPromotionDate", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="mdPromotionDateComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="mdPromotionDateComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="candidatePartnerPipeline" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="candidatePartnerPipeline", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="partnerPromotionDateComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="partnerPromotionDateComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="clientConsiderationComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="clientConsiderationComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rationalForNomination" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="rationalForNomination", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isPcaob" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isPcaob", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isIsa" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isIsa", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isifrsb" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isIfrsb", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isusgaapb" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isUsGaapb", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isaicpa" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isAicpa", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pcaoblevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="pcaobLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isalevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isaLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ifrsblevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="ifrsbLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="usgaapblevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="usGaapbLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="aicpalevel" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="aicpaLevel", columnDefinition="VARCHAR(10)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="recommendeddppgroupid" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="recommendedDppGroupId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroup" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroup", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroupOtherComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroupOtherComment", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleConsideration" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleConsideration", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isotherlanguage" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isOtherLanguage", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="languageotherthaneng" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="languageOtherThanEng", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="hasCpaLicense" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="hasCpaLicense", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="statesforcpalicence" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="statesForCpaLicence", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="primaryindustryid" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="primaryIndustryId", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="industry" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="industry", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="primaryindustryother" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="primaryIndustryOther", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isPotentialSecFasbCandidate" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isPotentialSec_FasbCandidate", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isAqspNomination" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isAqspNomination", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="anticipatedStartDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="anticipatedStartDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="anticipatedEndDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="anticipatedEndDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isAdditionalFollowUpReq" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isAdditionalFollowUpReq", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isReapprovedByBU" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isReapprovedByBU", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="operationsComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="operationsComments", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isAQR1or2" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isAQR1or2", columnDefinition="VARCHAR(5)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isCandidateGoodStanding" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isCandidateGoodStanding", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isVettingRequired" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isVettingRequired", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="hrComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="hrComments", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="vettingComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="vettingComments", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isOpsAdditionalVettingReq" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isOpsAdditionalVettingReq", columnDefinition="VARCHAR(5)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="mdPromotionDateHR" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="mdPromotionDateHR", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="partnerPromotionDateHR" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="partnerPromotionDateHR", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="negativeInspectionFindings" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="negativeInspectionFindings", columnDefinition="VARCHAR(3)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="inspectionComments" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="inspectionComments", columnDefinition="VARCHAR(1500)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="yearsofServiceHR" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="yearsofServiceHR", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isinterviewrequested" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isInterviewRequested", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isinterviewconducted" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isInterviewConducted", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isreadyforonboarding" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isReadyForOnboarding", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="interviewerNames" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="interviewerNames", columnDefinition="text")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="supportExtensionOfOffer" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="supportExtensionOfOffer", columnDefinition="text")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="candidateProjectedStartDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="candidateProjectedStartDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rotationEndDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="rotationEndDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="candidateDetailsDppGroup" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="candidateDetailsdppGroup", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="costCenter" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="costCenter", columnDefinition="VARCHAR(255)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isactive" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isActive", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdby" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdon" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedby" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedon" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
