<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:CAW"
  xmlns:tns="urn:com:appian:types:CAW" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="CAW_CoreAskDetail">
    <xsd:annotation>
      <xsd:appinfo source="appian.jpa">@Table(name="CAW_CoreAskDetail")</xsd:appinfo>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ebb8-de58-8000-9cc5-7f0000014e7a</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000e6a2-9bc3-8000-87ce-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6ab-fab3-8000-8cf5-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6bb-8734-8000-9398-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6bb-8c40-8000-93a2-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e6c4-fb77-8000-97e7-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000e721-7a8b-8000-b717-7f0000014e7a"/>
            <ns2:historyInfo versionUuid="0000ebb8-de58-8000-9cc5-7f0000014e7a"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[cdt for CAW_CoreAskDetail]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="askDetailId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id @GeneratedValue @Column(name="askDetailId", nullable=false, unique=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="askId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="askId", nullable=false, columnDefinition="INT") @JoinColumn(name="askId")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="coreAskName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="coreAskName", columnDefinition="VARCHAR(200)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="dppGroupId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="dppGroupId", nullable=false, columnDefinition="INT") @JoinColumn(name="dppGroupId")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="needReasonId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="needReasonId", nullable=true, columnDefinition="INT") @JoinColumn(name="needReasonId")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="employeeId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="employeeId", nullable=true, columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="outgoingResource" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="outGoingResource", columnDefinition="VARCHAR(300)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="levelNeedId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="levelNeedId", nullable=true, columnDefinition="INT") @JoinColumn(name="levelNeedId")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="generalSpecialityNeedId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="generalSpecialityNeedId", nullable=true, columnDefinition="INT") @JoinColumn(name="generalSpecialityNeedId")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="generalSpecialityNeedComment" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="generalSpecialityNeedComment", columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="headCountAmount" nillable="true" type="xsd:double">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="headCountAmount", nullable=true, columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="fteAmount" nillable="true" type="xsd:double">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="fteAmount", nullable=true, columnDefinition="DECIMAL")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="endDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="endDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="projectedStartDate" nillable="true" type="xsd:date">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="projectedStartDate", columnDefinition="DATE")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleSummary" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleSummary", nullable=true, columnDefinition="VARCHAR(2000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="titlingCategory" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="titlingCategory", nullable=true, columnDefinition="VARCHAR(300)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="pml" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="pml", nullable=true, columnDefinition="VARCHAR(99)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="transitionalCoach" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="transitionalCoach", nullable=true, columnDefinition="VARCHAR(99)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleResponsibility" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleResponsibility", nullable=true, columnDefinition="VARCHAR(2000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="roleQualification" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="roleQualification", nullable=true, columnDefinition="VARCHAR(2000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="rolePostingId" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="rolePostingId", nullable=true, columnDefinition="INT") @JoinColumn(name="rolePostingId")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="postingReqNumber" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="postingReqNumber", nullable=true, columnDefinition="VARCHAR(1000)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isCompleted" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isCompleted", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isActive" nillable="true" type="xsd:boolean">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="isActive", columnDefinition="BIT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="version" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="version", columnDefinition="INT")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="createdOn" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="createdOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedBy" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedBy", columnDefinition="VARCHAR(100)")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="modifiedOn" nillable="true" type="xsd:dateTime">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(name="modifiedOn", columnDefinition="TIMESTAMP")</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
